### ISSUE TITLE
[BUG] quickstart should qualify containers from docker.io for podmans benefit

### ISSUE THREAD

**Issue by nerscchris** [OpenCHAMI/deployment-recipes#58]
Hi there,

Experimenting with `podman-compose` to do the quickstart (after working around a bug in podman on Pop-OS (based on Ubuntu) where it sets the CNI network version incorrectly) I found it couldn't pull the hydra and postgres containers because the names weren't prefixed with `docker.io/` at the start.

Adding that prefix to the image definitions in `jwt-security.yml` and `postgres.yml` resolved that issue.

For example:
```diff
chris@pop-os:~/Code/OCHAMI/deployment-recipes/quickstart$ git diff jwt-security.yml
diff --git a/quickstart/jwt-security.yml b/quickstart/jwt-security.yml
index 6fa5766..c7e1ad4 100644
--- a/quickstart/jwt-security.yml
+++ b/quickstart/jwt-security.yml
@@ -47,7 +47,7 @@ services:
       opaal-idp:
         condition: service_healthy
   hydra:
-    image: oryd/hydra:v2.2.0-rc.3
+    image: docker.io/oryd/hydra:v2.2.0-rc.3
     container_name: hydra
     hostname: hydra
     healthcheck:
@@ -77,7 +77,7 @@ services:
     networks:
       - jwt-internal
   hydra-migrate:
-    image: oryd/hydra:v2.2.0-rc.3
+    image: docker.io/oryd/hydra:v2.2.0-rc.3
     container_name: hydra-migrate
     hostname: hydra-migrate
     environment:
```
and:
```diff
 services:
   postgres: # Postgres
-    image: postgres:11.5-alpine
+    image: docker.io/postgres:11.5-alpine
```
Can't show the full diff for the postgres one as I've got Chris Harris's fixes from his PR's already there too.

All the best,
Chris

**Comment by alexlovelltroy** [comment]
Thanks for the report.  You're right!  We should make these fully qualified containers rather than shorthand.  I'll take a crack at this later today.

You may also be interested in our experiments with podman-quadlets which seeks to handle dependencies and container organization in a more systemD-like and podman-native way.  The branch isn't ready for merge yet, but it may provide you with some food for thought.  https://github.com/OpenCHAMI/deployment-recipes/tree/trcotton/podman-quadlets
